definitions:
  entity.AddSysAdminDto:
    properties:
      deptId:
        description: 部门id
        type: integer
      email:
        description: 邮箱
        type: string
      nickname:
        description: 昵称
        type: string
      note:
        description: 备注
        type: string
      password:
        description: 密码
        type: string
      phone:
        description: 手机号
        type: string
      postId:
        description: 岗位id
        type: integer
      rostId:
        description: 角色id
        type: integer
      status:
        description: 状态：1->启用,2->禁用
        type: integer
      username:
        description: 用户名
        type: string
    required:
    - deptId
    - email
    - nickname
    - password
    - phone
    - postId
    - rostId
    - status
    - username
    type: object
  entity.LoginDto:
    properties:
      captcha:
        description: 验证码
        maxLength: 6
        minLength: 4
        type: string
      idKey:
        description: 验证码key
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - captcha
    - idKey
    - password
    - username
    type: object
  response.Result:
    properties:
      code:
        description: 状态码
        type: integer
      data:
        description: 数据
      message:
        description: 消息
        type: string
    type: object
info:
  contact: {}
  description: 后台管理系统API接口文档
  title: 通用后台管理系统
  version: "1.0"
paths:
  /api/admin/add:
    post:
      description: 新增用户接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.AddSysAdminDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - ApiKeyAuth: []
      summary: 新增用户接口
      tags:
      - 用户管理
  /api/captcha:
    get:
      description: 验证码接口
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 验证码接口
      tags:
      - 验证码
  /api/login:
    post:
      description: 用户登录接口
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.LoginDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      summary: 用户登录接口
      tags:
      - 用户管理
  /api/post/list:
    get:
      description: 获取岗位列表
      parameters:
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        type: integer
      - description: 岗位名称
        in: query
        name: postName
        type: string
      - description: 岗位状态:1启用,2禁用
        in: query
        name: postStatus
        type: string
      - description: 开始时间
        in: query
        name: beginTime
        type: string
      - description: 结束时间
        in: query
        name: endTime
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Result'
      security:
      - ApiKeyAuth: []
      summary: 岗位列表(分页)
      tags:
      - 岗位管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
